{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.namespaced | ternary "RoleBinding" "ClusterRoleBinding" }}
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubernetes-event-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ include "kubernetes-event-exporter.namespace" . }}
    name: {{ include "kubernetes-event-exporter.fullname" . }}
{{- end }}
